[profile.default]
evm_version = 'cancun'
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./"},   
    { access = "read-write", path = "./script"},
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
